name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare pnpm
        uses: pnpm/action-setup@v2

      - name: Prepare Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: ESLint
        run: pnpm run lint

      - name: Prettier code style check
        run: pnpm prettier . --check

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
